# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flight_booking_pb2 as flight__booking__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flight_booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightBookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBookings = channel.unary_unary(
                '/flightbookings.FlightBookingService/ListBookings',
                request_serializer=flight__booking__pb2.Empty.SerializeToString,
                response_deserializer=flight__booking__pb2.BookingList.FromString,
                _registered_method=True)
        self.AddBooking = channel.unary_unary(
                '/flightbookings.FlightBookingService/AddBooking',
                request_serializer=flight__booking__pb2.Booking.SerializeToString,
                response_deserializer=flight__booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.RemoveBooking = channel.unary_unary(
                '/flightbookings.FlightBookingService/RemoveBooking',
                request_serializer=flight__booking__pb2.BookingId.SerializeToString,
                response_deserializer=flight__booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.UpdateBooking = channel.unary_unary(
                '/flightbookings.FlightBookingService/UpdateBooking',
                request_serializer=flight__booking__pb2.Booking.SerializeToString,
                response_deserializer=flight__booking__pb2.BookingResponse.FromString,
                _registered_method=True)


class FlightBookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightBookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookings,
                    request_deserializer=flight__booking__pb2.Empty.FromString,
                    response_serializer=flight__booking__pb2.BookingList.SerializeToString,
            ),
            'AddBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBooking,
                    request_deserializer=flight__booking__pb2.Booking.FromString,
                    response_serializer=flight__booking__pb2.BookingResponse.SerializeToString,
            ),
            'RemoveBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBooking,
                    request_deserializer=flight__booking__pb2.BookingId.FromString,
                    response_serializer=flight__booking__pb2.BookingResponse.SerializeToString,
            ),
            'UpdateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBooking,
                    request_deserializer=flight__booking__pb2.Booking.FromString,
                    response_serializer=flight__booking__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flightbookings.FlightBookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flightbookings.FlightBookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightBookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flightbookings.FlightBookingService/ListBookings',
            flight__booking__pb2.Empty.SerializeToString,
            flight__booking__pb2.BookingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flightbookings.FlightBookingService/AddBooking',
            flight__booking__pb2.Booking.SerializeToString,
            flight__booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flightbookings.FlightBookingService/RemoveBooking',
            flight__booking__pb2.BookingId.SerializeToString,
            flight__booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flightbookings.FlightBookingService/UpdateBooking',
            flight__booking__pb2.Booking.SerializeToString,
            flight__booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
