# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flight_booking.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'flight_booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66light_booking.proto\x12\x0e\x66lightbookings\"\xa8\x01\n\x07\x42ooking\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0epassenger_name\x18\x02 \x01(\t\x12\x17\n\x0fpassenger_email\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65parture_date\x18\x04 \x01(\t\x12\x14\n\x0c\x61rrival_date\x18\x05 \x01(\t\x12\x19\n\x11\x64\x65parture_airport\x18\x06 \x01(\t\x12\x17\n\x0f\x61rrival_airport\x18\x07 \x01(\t\"\x07\n\x05\x45mpty\"8\n\x0b\x42ookingList\x12)\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x17.flightbookings.Booking\"\x17\n\tBookingId\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0f\x42ookingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x02\n\x14\x46lightBookingService\x12\x42\n\x0cListBookings\x12\x15.flightbookings.Empty\x1a\x1b.flightbookings.BookingList\x12\x46\n\nAddBooking\x12\x17.flightbookings.Booking\x1a\x1f.flightbookings.BookingResponse\x12K\n\rRemoveBooking\x12\x19.flightbookings.BookingId\x1a\x1f.flightbookings.BookingResponse\x12I\n\rUpdateBooking\x12\x17.flightbookings.Booking\x1a\x1f.flightbookings.BookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKING']._serialized_start=41
  _globals['_BOOKING']._serialized_end=209
  _globals['_EMPTY']._serialized_start=211
  _globals['_EMPTY']._serialized_end=218
  _globals['_BOOKINGLIST']._serialized_start=220
  _globals['_BOOKINGLIST']._serialized_end=276
  _globals['_BOOKINGID']._serialized_start=278
  _globals['_BOOKINGID']._serialized_end=301
  _globals['_BOOKINGRESPONSE']._serialized_start=303
  _globals['_BOOKINGRESPONSE']._serialized_end=354
  _globals['_FLIGHTBOOKINGSERVICE']._serialized_start=357
  _globals['_FLIGHTBOOKINGSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
